---
version: 2.1

orbs:
  python: circleci/python@1.1.0

jobs:
  remote-access:
    executor: python/default
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            pip install -r require.txt
      - run:
          name: Run Python script
          command: python remote_access.py

    

workflows:
  version: 2
  connect-and-access:
    jobs:
      - remote-access
