---
version: 2.1

orbs:
  python: circleci/python@1.1.0

jobs:
  remote-access:
    executor: python/default
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            pip install -r require.txt
      - run:
          name: Run api script
          command: python app.py
      - run:
          name: Run remote_machine script
          command: python remote_machine.py
      - run:
          name: Run demo script
          command: python demo.py

workflows:
  version: 2
  connect-and-access:
    jobs:
      - remote-access
