---
version: 2.1

orbs:
  python: circleci/python@1.1.0

jobs:
  remote-access:
    executor: python/default
    steps:
      - checkout
      - run:
          name: Install Jupyter
          command: |
            pip install jupyter
            pip install -r require.txt
      - run:
          name: Run remote_machine script
          command: python remote_machine.py
      - run:
          name: Run demo script
          command: |
            jupyter nbconvert --to notebook --execute demo.ipynb

workflows:
  version: 2
  connect-and-access:
    jobs:
      - remote-access

