---
version: 2.1

orbs:
  python: circleci/python@1.1.0

jobs:
  remote-access:
    executor: python/default
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            pip install -r require.txt
      - run:
          name: Run sdk file
          command: python remote_access_sdk.py      
      - run:
          name: Run test script
          command: python test_script.py
            

workflows:
  version: 2
  connect-and-access:
    jobs:
      - remote-access
