---
version: 2.1

orbs:
  python: circleci/python@1.1.0

jobs:
  remote-access:
    executor: python/default
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            pip install -r require.txt
      - run:
          name: retrieving creds
          command: python access.py  
      - run:
          name: accessing the machine
          command: python machine_access.py       
      - run:
          name: Run demo script
          command: python demo1.py
            

workflows:
  version: 2
  connect-and-access:
    jobs:
      - remote-access

